### PR TITLE
Add SkipTestTrait for ignoring/skipping protocol tests

### PR DESCRIPTION
**Pull request by alextwoods**
*Description of changes:*
Add a trait to allow skipping a protocol test.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mullermp — COMMENTED** [review]
Why the need for two trait classes?

**Comment by alextwoods** [comment]
There is only one trait class (SkipTestsTrait) - but it defines a list of tests to skip.
We can only apply the trait once per operation, but we may need to skip multiple tests, so we accept a list.  This works identically to the way protocol test traits are defined.

**Comment by mullermp** [comment]
But there's a trait/SkipTest.java and trait/SkipTestsTrait.java

**Comment by alextwoods** [comment]
We could move the SkipTest class somewhere else if you prefer, but I followed the design for the HttpResponseTestsTrait and HttpResponseTestCase class  (both are in the software.amazon.smithy.protocoltests.traits package).

**Review by mullermp — APPROVED** [review]

**Pull request merged**
